In [33]:
import pandas as pd

In [34]:
df=pd.read_csv("C:/Users/devik/Downloads/titanic.csv")

In [35]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [37]:
df1=df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')
df1.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [38]:
X = df1.drop("Survived",axis="columns")
X.head()

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [39]:
Y=df1.Survived
Y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [40]:
dummies=pd.get_dummies(X.Sex).astype(int)
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [41]:
X=pd.concat([dummies,X],axis="columns")
X.head()

   female  male  Pclass     Sex   Age     Fare
0       0     1       3    male  22.0   7.2500
1       1     0       1  female  38.0  71.2833
2       1     0       3  female  26.0   7.9250
3       1     0       1  female  35.0  53.1000
4       0     1       3    male  35.0   8.0500

In [42]:
X=X.drop("Sex",axis="columns")
X.head()

   female  male  Pclass   Age     Fare
0       0     1       3  22.0   7.2500
1       1     0       1  38.0  71.2833
2       1     0       3  26.0   7.9250
3       1     0       1  35.0  53.1000
4       0     1       3  35.0   8.0500

In [73]:
X.columns[X.isna().any()]

Index(['Age'], dtype='object')

In [77]:
X["Age"]=X.Age.fillna(X.Age.mean())
X.head()

   female  male  Pclass   Age     Fare
0       0     1       3  22.0   7.2500
1       1     0       1  38.0  71.2833
2       1     0       3  26.0   7.9250
3       1     0       1  35.0  53.1000
4       0     1       3  35.0   8.0500

In [81]:
X.Age.isna().sum()

0

In [83]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [85]:
from sklearn.naive_bayes import GaussianNB
NB = GaussianNB()

In [87]:
NB.fit(X_train,Y_train)

GaussianNB()

In [91]:
NB.score(X_test,Y_test)

0.7541899441340782

In [99]:
NB.predict_proba(X_test[:10])

array([[0.99018472, 0.00981528],
       [0.98974872, 0.01025128],
       [0.00197722, 0.99802278],
       [0.99054792, 0.00945208],
       [0.99038991, 0.00961009],
       [0.99016859, 0.00983141],
       [0.99022073, 0.00977927],
       [0.99042845, 0.00957155],
       [0.06577543, 0.93422457],
       [0.97752391, 0.02247609]])

In [101]:
NB.predict(X_test[:10])

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [107]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train,Y_train,cv=10)

array([0.75      , 0.83333333, 0.81690141, 0.81690141, 0.77464789,
       0.83098592, 0.67605634, 0.74647887, 0.8028169 , 0.81690141])